# Быстрая регистрация нового аккаунта Vercel

echo "🆕 Создание нового аккаунта Vercel для NORMALDANCE..."
echo ""
echo "📋 Пошаговая инструкция:"
echo ""
echo "1. 🌐 Откройте Vercel:"
echo "   https://vercel.com/signup"
echo ""
echo "2. 🔗 Войдите через GitHub:"
echo "   - Нажмите 'Continue with GitHub'"
echo "   - Создайте новый GitHub аккаунт (если нужно)"
echo "   - Email: ваш-email@gmail.com"
echo "   - Username: normaldance-dev"
echo ""
echo "3. 📁 Создайте новый репозиторий GitHub:"
echo "   - Название: normaldance"
echo "   - Описание: Web3 Music Platform"
echo "   - Публичный или приватный"
echo ""
echo "4. 📤 Загрузите код проекта:"
echo "   git clone https://github.com/your-username/normaldance.git"
echo "   cd normaldance"
echo "   # Скопируйте файлы проекта"
echo "   git add ."
echo "   git commit -m 'Initial commit'"
echo "   git push origin main"
echo ""
echo "5. 🚀 Подключите к Vercel:"
echo "   - Войдите в новый аккаунт Vercel"
echo "   - Нажмите 'New Project'"
echo "   - Импортируйте GitHub репозиторий"
echo "   - Выберите NORMALDANCE проект"
echo ""
echo "6. ⚙️ Настройте проект:"
echo "   - Framework Preset: Next.js"
echo "   - Build Command: npm run build"
echo "   - Output Directory: .next"
echo ""
echo "7. 🔧 Добавьте переменные окружения:"
echo "   NODE_ENV=production"
echo "   NEXT_TELEMETRY_DISABLED=1"
echo "   NEXTAUTH_URL=https://your-project.vercel.app"
echo "   NEXTAUTH_SECRET=your_super_secret_key_change_me"
echo ""
echo "8. 🎉 Деплойте проект:"
echo "   - Нажмите 'Deploy'"
echo "   - Ждите завершения (2-3 минуты)"
echo "   - Получите URL: https://your-project.vercel.app"
echo ""
echo "📊 Что получите бесплатно:"
echo "  ✅ 100GB bandwidth в месяц"
echo "  ✅ 100GB storage"
echo "  ✅ 100 serverless functions"
echo "  ✅ Unlimited static sites"
echo "  ✅ 1 custom domain"
echo "  ✅ SSL сертификаты"
echo "  ✅ Глобальный CDN"
echo ""
echo "🎯 Преимущества нового аккаунта:"
echo "  ✅ Свежие бесплатные лимиты"
echo "  ✅ Чистая среда без конфликтов"
echo "  ✅ Лучшая организация проекта"
echo "  ✅ Отдельные настройки"
echo ""
echo "💡 Советы:"
echo "  ✅ Используйте отдельный email"
echo "  ✅ Создайте отдельный GitHub аккаунт"
echo "  ✅ Сохраните логин и пароль"
echo "  ✅ Настройте 2FA для безопасности"
echo ""
echo "🚀 Готово! Теперь можете создать новый аккаунт Vercel."
